/*  SPDX-License-Identifier: LGPL-2.1-or-later
 *
 *  librdsparser – Radio Data System parser library
 *  Copyright (C) 2024  Konrad Kosmatka
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 */

#include <stdint.h>
#include <stdbool.h>
#include <librdsparser.h>

static const char *rdsparser_country_name_lut[] =
{
    "Albania",
    "Estonia",
    "Algeria",
    "Ethiopia",
    "Andorra",
    "Angola",
    "Finland",
    "Armenia",
    "France",
    "Ascension Island",
    "Gabon",
    "Austria",
    "Gambia",
    "Azerbaijan",
    "Georgia",
    "Germany",
    "Bahrein",
    "Ghana",
    "Belarus",
    "Gibraltar",
    "Belgium",
    "Greece",
    "Benin",
    "Guinea",
    "Bosnia Herzegovina",
    "Guinea-Bissau",
    "Botswana",
    "Hungary",
    "Bulgaria",
    "Iceland",
    "Burkina Faso",
    "Iraq",
    "Burundi",
    "Ireland",
    "Cabinda",
    "Israel",
    "Cameroon",
    "Italy",
    "Jordan",
    "Cape Verde",
    "Kazakhstan",
    "Central African Republic",
    "Kenya",
    "Chad",
    "Kosovo",
    "Comoros",
    "Kuwait",
    "DR Congo",
    "Kyrgyzstan",
    "Republic of Congo",
    "Latvia",
    "Cote d'Ivoire",
    "Lebanon",
    "Croatia",
    "Lesotho",
    "Cyprus",
    "Liberia",
    "Czechia",
    "Libya",
    "Denmark",
    "Liechtenstein",
    "Djiboutia",
    "Lithuania",
    "Egypt",
    "Luxembourg",
    "Equatorial Guinea",
    "Macedonia",
    "Eritrea",
    "Madagascar",
    "Seychelles",
    "Malawi",
    "Sierra Leone",
    "Mali",
    "Slovakia",
    "Malta",
    "Slovenia",
    "Mauritania",
    "Somalia",
    "Mauritius",
    "South Africa",
    "Moldova",
    "South Sudan",
    "Monaco",
    "Spain",
    "Mongolia",
    "Sudan",
    "Montenegro",
    "Swaziland",
    "Morocco",
    "Sweden",
    "Mozambique",
    "Switzerland",
    "Namibia",
    "Syria",
    "Netherlands",
    "Tajikistan",
    "Niger",
    "Tanzania",
    "Nigeria",
    "Togo",
    "Norway",
    "Tunisia",
    "Oman",
    "Turkey",
    "Palestine",
    "Turkmenistan",
    "Poland",
    "Uganda",
    "Portugal",
    "Ukraine",
    "Qatar",
    "United Arab Emirates",
    "Romania",
    "United Kingdom",
    "Russia",
    "Uzbekistan",
    "Rwanda",
    "Vatican",
    "San Marino",
    "Western Sahara",
    "Sao Tome and Principe",
    "Yemen",
    "Saudi Arabia",
    "Zambia",
    "Senegal",
    "Zimbabwe",
    "Serbia",
    "Anguilla",
    "Guyana",
    "Antigua and Barbuda",
    "Haiti",
    "Argentina",
    "Honduras",
    "Aruba",
    "Jamaica",
    "Bahamas",
    "Martinique",
    "Barbados",
    "Mexico",
    "Belize",
    "Montserrat",
    "Brazil/Bermuda",
    "Brazil/AN",
    "Bolivia",
    "Nicaragua",
    "Brazil",
    "Panama",
    "Canada",
    "Paraguay",
    "Cayman Islands",
    "Peru",
    "Chile",
    "USA/VI/PR",
    "Colombia",
    "St. Kitts",
    "Costa Rica",
    "St. Lucia",
    "Cuba",
    "St. Pierre and Miquelon",
    "Dominica",
    "St. Vincent",
    "Dominican Republic",
    "Suriname",
    "El Salvador",
    "Trinidad and Tobago",
    "Turks and Caicos islands",
    "Falkland Islands",
    "Greenland",
    "Uruguay",
    "Grenada",
    "Venezuela",
    "Guadeloupe",
    "Virgin Islands",
    "Guatemala",
    "Afghanistan",
    "South Korea",
    "Laos",
    "Australia Capital Territory",
    "Macao",
    "Australia New South Wales",
    "Malaysia",
    "Australia Victoria",
    "Maldives",
    "Australia Queensland",
    "Marshall Islands",
    "Australia South Australia",
    "Micronesia",
    "Australia Western Australia",
    "Myanmar",
    "Australia Tasmania",
    "Nauru",
    "Australia Northern Territory",
    "Nepal",
    "Bangladesh",
    "New Zealand",
    "Bhutan",
    "Pakistan",
    "Brunei Darussalam",
    "Papua New Guinea",
    "Cambodia",
    "Philippines",
    "China",
    "Samoa",
    "Singapore",
    "Solomon Islands",
    "Fiji",
    "Sri Lanka",
    "Hong Kong",
    "Taiwan",
    "India",
    "Thailand",
    "Indonesia",
    "Tonga",
    "Iran",
    "Vanuatu",
    "Japan",
    "Vietnam",
    "Kiribati",
    "North Korea",
    "Brazil/Equator"
};

static const char *rdsparser_country_iso_lut[] =
{
    "AL",
    "EE",
    "DZ",
    "ET",
    "AD",
    "AO",
    "FI",
    "AM",
    "FR",
    "SH",
    "GA",
    "AT",
    "GM",
    "AZ",
    "GE",
    "DE",
    "BH",
    "GH",
    "BY",
    "GI",
    "BE",
    "GR",
    "BJ",
    "GN",
    "BA",
    "GW",
    "BW",
    "HU",
    "BG",
    "IS",
    "BF",
    "IQ",
    "BI",
    "IE",
    "--",
    "IL",
    "CM",
    "IT",
    "JO",
    "CV",
    "KZ",
    "CF",
    "KE",
    "TD",
    "XK",
    "KM",
    "KW",
    "CD",
    "KG",
    "CG",
    "LV",
    "CI",
    "LB",
    "HR",
    "LS",
    "CY",
    "LR",
    "CZ",
    "LY",
    "DK",
    "LI",
    "DJ",
    "LT",
    "EG",
    "LU",
    "GQ",
    "MK",
    "ER",
    "MG",
    "SC",
    "MW",
    "SL",
    "ML",
    "SK",
    "MT",
    "SI",
    "MR",
    "SO",
    "MU",
    "ZA",
    "MD",
    "SS",
    "MC",
    "ES",
    "MN",
    "SD",
    "ME",
    "SZ",
    "MA",
    "SE",
    "MZ",
    "CH",
    "NA",
    "SY",
    "NL",
    "TJ",
    "NE",
    "TZ",
    "NG",
    "TG",
    "NO",
    "TN",
    "OM",
    "TR",
    "PS",
    "TM",
    "PL",
    "UG",
    "PT",
    "UA",
    "QA",
    "AE",
    "RO",
    "GB",
    "RU",
    "UZ",
    "RW",
    "VA",
    "SM",
    "EH",
    "ST",
    "YE",
    "SA",
    "ZM",
    "SN",
    "ZW",
    "RS",
    "AI",
    "GY",
    "AG",
    "HT",
    "AR",
    "HN",
    "AW",
    "JM",
    "BS",
    "MQ",
    "BB",
    "MX",
    "BZ",
    "MS",
    "--",
    "--",
    "BO",
    "NI",
    "BR",
    "PA",
    "CA",
    "PY",
    "KY",
    "PE",
    "CL",
    "--",
    "CO",
    "KN",
    "CR",
    "LC",
    "CU",
    "PM",
    "DM",
    "VC",
    "DO",
    "SR",
    "SN",
    "TT",
    "TB",
    "FK",
    "GL",
    "UY",
    "GD",
    "VE",
    "GP",
    "VG",
    "GT",
    "AF",
    "KR",
    "LA",
    "AU",
    "MO",
    "AU",
    "MY",
    "AU",
    "MV",
    "AU",
    "MH",
    "AU",
    "FM",
    "AU",
    "MM",
    "AU",
    "NR",
    "AU",
    "NP",
    "BD",
    "NZ",
    "BT",
    "PK",
    "BN",
    "PG",
    "KH",
    "PH",
    "CN",
    "WS",
    "SG",
    "SB",
    "FJ",
    "LK",
    "HK",
    "TW",
    "IN",
    "TH",
    "ID",
    "TO",
    "IR",
    "VU",
    "JP",
    "VN",
    "KI",
    "KP",
    "--"
};

const char*
rdsparser_country_lookup(rdsparser_country_t   country,
                         const char          **lut,
                         const char           *unknown)
{
    if (country <= RDSPARSER_COUNTRY_UNKNOWN ||
        country >= RDSPARSER_COUNTRY_COUNT)
    {
        return unknown;
    }

    return lut[country - 1];
}

const char*
rdsparser_country_lookup_name(rdsparser_country_t country)
{
    static const char *unknown = "Unknown";
    return rdsparser_country_lookup(country, rdsparser_country_name_lut, unknown);
}

const char*
rdsparser_country_lookup_iso(rdsparser_country_t country)
{
    static const char *unknown = "??";
    return rdsparser_country_lookup(country, rdsparser_country_iso_lut, unknown);
}
