name: Windows build

on:
  release:
    types: [created]

jobs:
  build-msys2:
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch: [mingw64, mingw32]
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{matrix.arch}}
          install: >-
            git
            make
          pacboy: >-
            cmake:p
            gcc:p

      - name: Compile the project
        shell: msys2 {0}
        run : |
          cp -r build build-${{matrix.arch}}
          cd build-${{matrix.arch}}
          ./build-mingw.sh

      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build-${{matrix.arch}}/src/*.dll ./artifacts/
          move ./build-${{matrix.arch}}/src/*.a ./artifacts/
          zip -r "${{matrix.arch}}.zip" artifacts/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.arch}}
          path: ${{matrix.arch}}.zip

      - name: Upload assets to release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release upload "${{github.event.release.tag_name}}" "${{matrix.arch}}.zip"
