name: macOS build

on:
  release:
    types: [created]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake gcc

      - name: Build for macOS
        run: |
          cd build
          ./build-macos.sh

      - name: Move artifacts
        run: |
          mkdir artifacts
          mv ./build/src/*.dylib ./artifacts/
          mv ./build/src/*.a ./artifacts/
          zip -r macos.zip artifacts/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: macos.zip

      - name: Upload assets to release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release upload "${{github.event.release.tag_name}}" "macos.zip"
