name: GNU/Linux build

on:
  push:
    branches: [ "githubtest" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04
    
    strategy:
      matrix:
        arch: [x86, x86_64]
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add toolchain PPA
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
    
      - name: Install dependencies
        run: |
          sudo apt-get install -y cmake make
          case "${{ matrix.arch }}" in
            x86)
              sudo apt-get install -y gcc-multilib
              ;;
            x86|x86_64)
              sudo apt-get install -y gcc
              ;;
            arm)
              sudo apt-get install -y gcc-arm-linux-gnueabi
              ;;
            aarch64)
              sudo apt-get install -y gcc-aarch64-linux-gnu
              ;;
          esac

      - name: Build
        run: |
          cd build
          case "${{ matrix.arch }}" in
            x86)
              ./build.sh -DCMAKE_C_FLAGS=-m32
              ;;
            x86_64)
              ./build.sh
              ;;
            arm)
              ./build.sh -DCMAKE_SYSTEM_NAME=Linux \
                         -DCMAKE_SYSTEM_PROCESSOR=arm \
                         -DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc
              ;;
            aarch64)
              ./build.sh -DCMAKE_SYSTEM_NAME=Linux \
                         -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
                         -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc
              ;;
          esac

      - name: Move artifacts
        run: |
          mkdir artifacts
          mv ./build/src/*.so ./artifacts/
          mv ./build/src/*.a ./artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.arch}}
          path: artifacts
